version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - copyloopvar
    - dupl
    - ginkgolinter
    - goconst
    - gocyclo
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: api/
      - linters:
          - dupl
          - lll
        path: internal/
      - path: (.+)\.go$
        text: third_party$
      - path: (.+)\.go$
        text: builtin$
      - path: (.+)\.go$
        text: examples$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
