service:
  golangci-lint-version: 1.58.1 # Use the latest stable version

run:
  allow-parallel-runners: true

linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing

issues:
  # Exclude specific linters from specific paths.
  exclude-rules:
    - path: api/
      linters:
        - lll
    - path: internal/
      linters:
        - dupl
        - lll
  # Exclude all analysis from these paths.
  exclude:
    - third_party$
    - builtin$
    - examples$
  # The 'generated: lax' exclusion is now the default behavior, so it's not needed.