package golden

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/kndclark/kubetasker/test/utils"
	"github.com/stretchr/testify/require"
)

const (
	kustomizeGoldenFile      = "kustomize_golden.yaml"
	controllerHelmGoldenFile = "helm_golden.yaml"
	frontendStaticGoldenFile = "frontend_static_golden.yaml"
	frontendHelmGoldenFile   = "frontend_helm_golden.yaml"
	expectedKustomizeVersion = "v5.3.0" // Define the expected version
	expectedHelmVersion      = "v3."    // We can check for a major version
)

// TestPreHelmGoldenFile compares the current kustomize output against a "golden" file.
// This test is designed to catch any unintended changes to the Kubernetes manifests
// before they are migrated to Helm.
//
// If this test fails, it means the manifests generated by `kustomize build config/default`
// have changed.
//
// To update the golden file, run:
// make golden-update
func TestGoldenFiles(t *testing.T) {
	// Get the root of the project
	t.Log("Finding project root...")
	projectRoot, err := utils.GetProjectDir()
	require.NoError(t, err, "Failed to get project root")
	t.Logf("Project root found at: %s", projectRoot)

	t.Run("KustomizeOutput", func(t *testing.T) {
		// Run kustomize build
		t.Log("Running kustomize build...")
		kustomizePath := filepath.Join(projectRoot, "config", "default")
		cmd := exec.Command("kustomize", "build", kustomizePath)
		output, err := cmd.CombinedOutput()
		require.NoError(t, err, "Failed to run kustomize build: %s", string(output))

		// Compare with the golden file
		t.Log("Reading kustomize golden file...")
		goldenFile := filepath.Join(projectRoot, "test", "golden", kustomizeGoldenFile) // Corrected variable name
		expected, err := os.ReadFile(goldenFile)
		require.NoError(t, err, "Failed to read golden file: %s", goldenFile)

		t.Log("Comparing kustomize output with golden file...")
		require.Equal(t, string(expected), string(output),
			"Kustomize output does not match the golden file. Run 'make golden-update' to update it.")
	})

	t.Run("ControllerHelmOutput", func(t *testing.T) {
		t.Log("Verifying helm version...")
		versionCmd := exec.Command("helm", "version")
		versionOutput, err := versionCmd.CombinedOutput()
		require.NoError(t, err, "Failed to run 'helm version': %s", string(versionOutput))
		require.Contains(t, string(versionOutput),
			expectedHelmVersion,
			"Incorrect helm version found. Expected %s.", expectedHelmVersion)
		t.Logf("Helm version %s confirmed.", expectedHelmVersion)

		// Run helm template
		releaseName := "kubetasker-controller-test"
		t.Logf("Running helm template for controller with release name '%s'...", releaseName)
		chartPath := filepath.Join(projectRoot, "kubetasker-controller")
		// We use --set to override values for a consistent test output
		cmd := exec.Command("helm", "template", releaseName, chartPath, "--set",
			"image.repository=ktasker.com/kubetasker", "--set", "image.tag=v0.0.1")
		output, err := cmd.CombinedOutput()
		require.NoError(t, err, "Failed to run helm template: %s", string(output))

		// Compare with the golden file
		t.Log("Reading helm golden file...")
		goldenFile := filepath.Join(projectRoot, "test", "golden", controllerHelmGoldenFile)
		expected, err := os.ReadFile(goldenFile)
		require.NoError(t, err, "Failed to read golden file: %s", goldenFile)

		t.Log("Comparing helm output with golden file...")
		require.Equal(t, string(expected), string(output),
			"Helm output does not match the golden file. Run 'make golden-update' to update it.")
	})

	t.Run("FrontendStaticOutput", func(t *testing.T) {
		// Read the static manifest
		t.Log("Reading static frontend manifest...")
		staticFile := filepath.Join(projectRoot, "kubetasker-frontend", "templates", "deployment.yaml")
		current, err := os.ReadFile(staticFile)
		require.NoError(t, err, "Failed to read static frontend manifest: %s", staticFile)

		// Compare with the golden file
		t.Log("Reading frontend static golden file...")
		goldenFile := filepath.Join(projectRoot, "test", "golden", frontendStaticGoldenFile)
		expected, err := os.ReadFile(goldenFile)
		require.NoError(t, err, "Failed to read golden file: %s", goldenFile)

		t.Log("Comparing static frontend manifest with golden file...")
		require.Equal(t, string(expected), string(current),
			"Static frontend manifest does not match the golden file. Run 'make golden-update' to update it.")
	})

	t.Run("FrontendHelmOutput", func(t *testing.T) {
		// Run helm template for the frontend
		releaseName := "kubetasker-frontend-test"
		t.Logf("Running helm template for frontend with release name '%s'...", releaseName)
		chartPath := filepath.Join(projectRoot, "kubetasker-frontend")
		cmd := exec.Command("helm", "template", releaseName, chartPath, "--set",
			"image.repository=ktasker.com/kubetasker-frontend", "--set", "image.tag=v0.0.1")
		output, err := cmd.CombinedOutput()
		require.NoError(t, err, "Failed to run helm template for frontend: %s", string(output))

		// Compare with the golden file
		t.Log("Reading frontend helm golden file...")
		goldenFile := filepath.Join(projectRoot, "test", "golden", frontendHelmGoldenFile)
		expected, err := os.ReadFile(goldenFile)
		require.NoError(t, err, "Failed to read golden file: %s", goldenFile)

		t.Log("Comparing frontend helm output with golden file...")
		require.Equal(t, string(expected), string(output),
			"Frontend helm output does not match the golden file. Run 'make golden-update' to update it.")
	})

	t.Run("UmbrellaChartOutput", func(t *testing.T) {
		umbrellaTests := []struct {
			env        string
			goldenFile string
		}{
			{env: "dev", goldenFile: "umbrella_dev_golden.yaml"},
			{env: "staging", goldenFile: "umbrella_staging_golden.yaml"},
			{env: "prod", goldenFile: "umbrella_prod_golden.yaml"},
		}

		chartPath := filepath.Join(projectRoot, "kubetasker")

		for _, tt := range umbrellaTests {
			t.Run(tt.env, func(t *testing.T) {
				releaseName := fmt.Sprintf("umbrella-%s", tt.env)
				t.Logf("Running helm template for umbrella chart '%s' env with release name '%s'...", tt.env, releaseName)

				valuesFile := filepath.Join(chartPath, fmt.Sprintf("values-%s.yaml", tt.env))
				cmd := exec.Command("helm", "template", releaseName, chartPath,
					"-f", valuesFile,
					// We set static images to ensure consistent output, as the chart version might change.
					"--set", "kubetasker-controller.image.repository=controller",
					"--set", "kubetasker-controller.image.tag=v0.0.1",
					"--set", "kubetasker-frontend.image.repository=ktasker.com/kubetasker-frontend",
					"--set", "kubetasker-frontend.image.tag=v0.0.1",
					// We must also disable the cert-manager parts, as they are cluster-dependent and not static.
					"--set", "kubetasker-controller.certManager.enabled=false")
				output, err := cmd.CombinedOutput()
				require.NoError(t, err, "Failed to run helm template for umbrella chart: %s", string(output))

				goldenFilePath := filepath.Join(projectRoot, "test", "golden", tt.goldenFile)
				expected, err := os.ReadFile(goldenFilePath)
				require.NoError(t, err, "Failed to read golden file: %s", goldenFilePath)

				require.Equal(t, string(expected), string(output), "Umbrella chart output for env '%s' does not match the golden file. Run 'make golden-update' to update it.", tt.env)
			})
		}
	})
}
