package golden

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

const (
	goldenFilePath           = "pre_helm_manifest.yaml"
	expectedKustomizeVersion = "v5.3.0" // Define the expected version
)

// TestPreHelmGoldenFile compares the current kustomize output against a "golden" file.
// This test is designed to catch any unintended changes to the Kubernetes manifests
// before they are migrated to Helm.
//
// If this test fails, it means the manifests generated by `kustomize build config/default`
// have changed.
//
// To update the golden file, run:
// make golden-update
func TestPreHelmGoldenFile(t *testing.T) {
	// Get the root of the project
	t.Log("Finding project root...")
	projectRoot, err := getProjectRoot()
	require.NoError(t, err, "Failed to get project root")
	t.Logf("Project root found at: %s", projectRoot)

	// Verify kustomize version
	t.Log("Verifying kustomize version...")
	versionCmd := exec.Command("kustomize", "version")
	versionOutput, err := versionCmd.CombinedOutput()
	require.NoError(t, err, "Failed to run 'kustomize version': %s", string(versionOutput))
	// The output might be complex, e.g., "v5.3.0\n" or "{kustomize/v5.3.0 ...}"
	require.Contains(t, string(versionOutput), expectedKustomizeVersion, "Incorrect kustomize version found. Expected %s.", expectedKustomizeVersion)
	t.Logf("Kustomize version %s confirmed.", expectedKustomizeVersion)

	// Run kustomize build
	t.Log("Running kustomize build...")
	kustomizePath := filepath.Join(projectRoot, "config", "default")
	cmd := exec.Command("kustomize", "build", kustomizePath)
	output, err := cmd.CombinedOutput()
	require.NoError(t, err, "Failed to run kustomize build: %s", string(output))

	// Compare with the golden file
	t.Log("Reading golden file...")
	goldenFile := filepath.Join(projectRoot, "test", "golden", goldenFilePath)
	expected, err := os.ReadFile(goldenFile)
	require.NoError(t, err, "Failed to read golden file: %s", goldenFile)

	t.Log("Comparing kustomize output with golden file...")
	require.Equal(t, string(expected), string(output), "Kustomize output does not match the golden file. Run 'make golden-update' to update it.")
}

func getProjectRoot() (string, error) {
	// A simple way to find the project root is by looking for the go.mod file.
	// This makes the test runnable from any subdirectory.
	return filepath.Abs("../..")
}
