apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubetasker-controller.fullname" . }}-manager-role
  labels:
    {{- include "kubetasker-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.ktasker.com
  resources:
  - jobrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.ktasker.com
  resources:
  - jobrequests/finalizers
  verbs:
  - update
- apiGroups:
  - task.ktasker.com
  resources:
  - jobrequests/status
  verbs:
  - get
  - patch
  - update